train:
  path_to_train: data/train/
  model_save: models/resnet_trashnet.pth

infer:
  path_to_val: data/val/
  model_path: models/resnet_trashnet.pth
  result_save: results/out.csv

resnet:
  no_epochs: 10
  lr: 1e-4
  weights: DEFAULT
  num_classes: 6
